version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    environment:
      - "JEKYLL_GITHUB_TOKEN:d22d2e6aaf0cfecd2bfbb7daecd94edb46bffc0a"
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    tty: true